---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: redis-app-deployment
   labels: 
      type: redis-app
spec: 
   selector: 
      matchLabels: 
         type: redis-app
   template: 
      metadata: 
         name: redis-app-pod
         labels: 
            type: redis-app
      spec: 
         containers: 
            - name: myredis
              image: redis
---
apiVersion: v1
kind: Service
metadata: 
   name: redis-app-service
   labels: 
      type: redis-app
spec: 
   ports: 
      - targetPort: 6379
        port: 6379
   selector: 
      type: redis-app

