apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: myresultapp
  name: myresultapp
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myresultapp
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: myresultapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
