apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: myvotingapp
  name: myvotingapp
spec:
  replicas: 2
  selector: 
  matchLabels: 
     type: myvotingapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myvotingapp
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: myvotingapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
