apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: workerapp
  name: workerapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workerapp
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: workerapp
        resources: {}
      restartPolicy: Always
status: {}
